// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pingpong.proto

#include "pingpong.pb.h"
#include "pingpong.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace dy {

static const char* PingPongService_method_names[] = {
  "/dy.PingPongService/pingpong",
};

std::unique_ptr< PingPongService::Stub> PingPongService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PingPongService::Stub> stub(new PingPongService::Stub(channel, options));
  return stub;
}

PingPongService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_pingpong_(PingPongService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PingPongService::Stub::pingpong(::grpc::ClientContext* context, const ::dy::Ping& request, ::dy::Pong* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dy::Ping, ::dy::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_pingpong_, context, request, response);
}

void PingPongService::Stub::async::pingpong(::grpc::ClientContext* context, const ::dy::Ping* request, ::dy::Pong* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dy::Ping, ::dy::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_pingpong_, context, request, response, std::move(f));
}

void PingPongService::Stub::async::pingpong(::grpc::ClientContext* context, const ::dy::Ping* request, ::dy::Pong* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_pingpong_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dy::Pong>* PingPongService::Stub::PrepareAsyncpingpongRaw(::grpc::ClientContext* context, const ::dy::Ping& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dy::Pong, ::dy::Ping, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_pingpong_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dy::Pong>* PingPongService::Stub::AsyncpingpongRaw(::grpc::ClientContext* context, const ::dy::Ping& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpingpongRaw(context, request, cq);
  result->StartCall();
  return result;
}

PingPongService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PingPongService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PingPongService::Service, ::dy::Ping, ::dy::Pong, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PingPongService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dy::Ping* req,
             ::dy::Pong* resp) {
               return service->pingpong(ctx, req, resp);
             }, this)));
}

PingPongService::Service::~Service() {
}

::grpc::Status PingPongService::Service::pingpong(::grpc::ServerContext* context, const ::dy::Ping* request, ::dy::Pong* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dy

